server:
  port: 8088

spring:

  application:
    name: cart-service

  redis:
    host: 39.106.106.51
    port: 6379
    password: 123456
    database: 1

eureka:
  client:
    service-url:
      defaultZone: http://39.106.106.51:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5