server:
  port: 10010

spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  routes:
    item-service: /item/** #路由到商品的微服务
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
  add-host-header: true

swagger:
  api:
    names: user,auth,item,cart

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms