server:
  port: 8086
spring:
  application:
    name: service-sms

  redis:
    host: 39.106.106.51
    port: 6379
    password: 123456
    timeout: 10000
    database: 1

  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672

leyou:
  sms:
    accessKeyId: LTAI4FoMzPWm54ZttWJy6au9
    accessKeySecret: znRW2zdRdaOyTj6ypPWcJQHz4O5ID3
    signName: 叶叶梨梨 #签名名称
    verifyCodeTemplate: SMS_177549277 #模板名称